#!/bin/bash
#Author: Vivek Gawande
#Script to multiply two matrices r1xc1 and r2xc2. Proceed with caution

declare -A a
declare -A b

read -p "Enter number of rows in A: " r1
read -p "Enter number of columns in A: " c1
read -p "Enter number of rows in B: " r2
read -p "Enter number of columns in B: " c2

if [ $c1 -ne $r2 ]
then
  echo Invalid input. The two matrices cannot be multiplied.
  exit
fi

echo "Enter elements of matrix A: "
for((i=0;i<r1;i++))
do
  for((j=0;j<c1;j++))
  do
    read a[$i,$j]
  done
done

echo "The matrix A is: "
for((i=0;i<r1;i++))
do
  for((j=0;j<c1;j++))
  do
    echo -n "${a[$i,$j]} "
  done
  echo
done

